version: "3"
services:
  jenkins_master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8080"
  jenkins_slave1:
    build:
      context: .
      dockerfile: Dockerfile.slave
    entrypoint:
      - java
      - '-jar'
      - '/usr/share/jenkins/slave.jar'
    ports:
      - "8098:49187"
    depends_on:
      - jenkins_master
